name: "Build Raper"
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  build:
    # Run on all label events (won't be duplicated) or all push events or on PR syncs not from the same repo
    if: (github.event_name == 'pull_request' && github.event.action == 'labeled') || github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.6.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Create Paperclip Jar
        run: ./gradlew createReobfPaperclipJar --stacktrace

      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v3
        with:
          name: raper-${{ steps.commit.outputs.short }}
          path: build/libs/raper-paperclip-*-reobf.jar