name: "Check Raper"
on:
  push:
    paths-ignore:
      - '.gitignore'
      - '.editorconfig'
      - 'README.md'
      - 'PATCHES-LICENSE'

jobs:
  build:
    # Run if not on main branch
    if: github.ref_name != 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.6.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace